# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimulatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimulatorUI(object):
    def setupUi(self, SimulatorUI):
        SimulatorUI.setObjectName("SimulatorUI")
        SimulatorUI.resize(636, 712)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/simulator.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SimulatorUI.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SimulatorUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(2, 0, 2, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.listViewDataInfo = QtWidgets.QListView(self.groupBox)
        self.listViewDataInfo.setObjectName("listViewDataInfo")
        self.gridLayout_8.addWidget(self.listViewDataInfo, 0, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 83))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEditValue = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEditValue.setObjectName("textEditValue")
        self.horizontalLayout.addWidget(self.textEditValue)
        self.pushButtonPublish = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButtonPublish.setObjectName("pushButtonPublish")
        self.horizontalLayout.addWidget(self.pushButtonPublish)
        self.gridLayout_9.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        SimulatorUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SimulatorUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        SimulatorUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SimulatorUI)
        self.statusbar.setObjectName("statusbar")
        SimulatorUI.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(SimulatorUI)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listViewDataDictionary = QtWidgets.QListView(self.dockWidgetContents)
        self.listViewDataDictionary.setObjectName("listViewDataDictionary")
        self.gridLayout_5.addWidget(self.listViewDataDictionary, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        SimulatorUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_3 = QtWidgets.QDockWidget(SimulatorUI)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.listViewLog = QtWidgets.QListView(self.dockWidgetContents_3)
        self.listViewLog.setObjectName("listViewLog")
        self.gridLayout_3.addWidget(self.listViewLog, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        SimulatorUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_3)
        self.toolBar = QtWidgets.QToolBar(SimulatorUI)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        SimulatorUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConnectMqtt = QtWidgets.QAction(SimulatorUI)
        self.actionConnectMqtt.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/connect.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectMqtt.setIcon(icon1)
        self.actionConnectMqtt.setObjectName("actionConnectMqtt")
        self.actionSetting = QtWidgets.QAction(SimulatorUI)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/set.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon2)
        self.actionSetting.setObjectName("actionSetting")
        self.action_Load_CSV = QtWidgets.QAction(SimulatorUI)
        self.action_Load_CSV.setObjectName("action_Load_CSV")
        self.action_Exit = QtWidgets.QAction(SimulatorUI)
        self.action_Exit.setObjectName("action_Exit")
        self.menu_File.addAction(self.action_Load_CSV)
        self.menu_File.addAction(self.action_Exit)
        self.menubar.addAction(self.menu_File.menuAction())
        self.toolBar.addAction(self.actionConnectMqtt)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSetting)

        self.retranslateUi(SimulatorUI)
        QtCore.QMetaObject.connectSlotsByName(SimulatorUI)

    def retranslateUi(self, SimulatorUI):
        _translate = QtCore.QCoreApplication.translate
        SimulatorUI.setWindowTitle(_translate("SimulatorUI", "Simulator"))
        self.groupBox.setTitle(_translate("SimulatorUI", "Data Information"))
        self.groupBox_2.setTitle(_translate("SimulatorUI", "Publish Data"))
        self.label.setText(_translate("SimulatorUI", "Value:"))
        self.pushButtonPublish.setText(_translate("SimulatorUI", "Publish"))
        self.menu_File.setTitle(_translate("SimulatorUI", "&File"))
        self.dockWidget.setWindowTitle(_translate("SimulatorUI", "Data Dictionary"))
        self.dockWidget_3.setWindowTitle(_translate("SimulatorUI", "Log"))
        self.toolBar.setWindowTitle(_translate("SimulatorUI", "toolBar"))
        self.actionConnectMqtt.setText(_translate("SimulatorUI", "ConnectMqtt"))
        self.actionSetting.setText(_translate("SimulatorUI", "Setting"))
        self.action_Load_CSV.setText(_translate("SimulatorUI", "&Load CSV"))
        self.action_Exit.setText(_translate("SimulatorUI", "&Exit"))

import simulator.uiresource.Simulator_rc
