# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SettingDlgUi.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingDialog(object):
    def setupUi(self, SettingDialog):
        SettingDialog.setObjectName("SettingDialog")
        SettingDialog.resize(640, 480)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/ico/Setting.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SettingDialog.setWindowIcon(icon)
        self.gridLayout = QtWidgets.QGridLayout(SettingDialog)
        self.gridLayout.setObjectName("gridLayout")
        self.status_label = QtWidgets.QLabel(SettingDialog)
        self.status_label.setText("")
        self.status_label.setObjectName("status_label")
        self.gridLayout.addWidget(self.status_label, 1, 0, 1, 2)
        self.close_push_button = QtWidgets.QPushButton(SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_push_button.sizePolicy().hasHeightForWidth())
        self.close_push_button.setSizePolicy(sizePolicy)
        self.close_push_button.setObjectName("close_push_button")
        self.gridLayout.addWidget(self.close_push_button, 1, 2, 1, 1)
        self.apply_push_button = QtWidgets.QPushButton(SettingDialog)
        self.apply_push_button.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.apply_push_button.sizePolicy().hasHeightForWidth())
        self.apply_push_button.setSizePolicy(sizePolicy)
        self.apply_push_button.setObjectName("apply_push_button")
        self.gridLayout.addWidget(self.apply_push_button, 1, 4, 1, 1)
        self.contents_list_widget = QtWidgets.QListWidget(SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contents_list_widget.sizePolicy().hasHeightForWidth())
        self.contents_list_widget.setSizePolicy(sizePolicy)
        self.contents_list_widget.setMaximumSize(QtCore.QSize(160, 16777215))
        self.contents_list_widget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.contents_list_widget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.contents_list_widget.setIconSize(QtCore.QSize(40, 40))
        self.contents_list_widget.setWordWrap(True)
        self.contents_list_widget.setObjectName("contents_list_widget")
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/ico/MqttConnectConfig.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.contents_list_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignVCenter)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/ico/MqttBrokerConfig.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.contents_list_widget.addItem(item)
        self.gridLayout.addWidget(self.contents_list_widget, 0, 0, 1, 1)
        self.page_stacked_widget = QtWidgets.QStackedWidget(SettingDialog)
        self.page_stacked_widget.setFrameShape(QtWidgets.QFrame.Box)
        self.page_stacked_widget.setObjectName("page_stacked_widget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_page_1 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_page_1.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_page_1.setObjectName("gridLayout_page_1")
        self.broker_address_line_edit = QtWidgets.QLineEdit(self.page_1)
        self.broker_address_line_edit.setObjectName("broker_address_line_edit")
        self.gridLayout_page_1.addWidget(self.broker_address_line_edit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.gridLayout_page_1.addWidget(self.label_2, 1, 0, 1, 1)
        self.broker_port_spin_box = QtWidgets.QSpinBox(self.page_1)
        self.broker_port_spin_box.setMaximum(65535)
        self.broker_port_spin_box.setProperty("value", 1883)
        self.broker_port_spin_box.setObjectName("broker_port_spin_box")
        self.gridLayout_page_1.addWidget(self.broker_port_spin_box, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_page_1.addWidget(self.label, 0, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_page_1.addItem(spacerItem, 2, 0, 1, 1)
        self.page_stacked_widget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.page_stacked_widget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.page_stacked_widget, 0, 1, 1, 4)
        self.ok_push_button = QtWidgets.QPushButton(SettingDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok_push_button.sizePolicy().hasHeightForWidth())
        self.ok_push_button.setSizePolicy(sizePolicy)
        self.ok_push_button.setObjectName("ok_push_button")
        self.gridLayout.addWidget(self.ok_push_button, 1, 3, 1, 1)

        self.retranslateUi(SettingDialog)
        self.page_stacked_widget.setCurrentIndex(0)
        self.close_push_button.clicked.connect(SettingDialog.reject)
        self.ok_push_button.clicked.connect(SettingDialog.accept)
        QtCore.QMetaObject.connectSlotsByName(SettingDialog)

    def retranslateUi(self, SettingDialog):
        _translate = QtCore.QCoreApplication.translate
        SettingDialog.setWindowTitle(_translate("SettingDialog", "Setting"))
        self.close_push_button.setText(_translate("SettingDialog", "Close"))
        self.apply_push_button.setText(_translate("SettingDialog", "Apply"))
        __sortingEnabled = self.contents_list_widget.isSortingEnabled()
        self.contents_list_widget.setSortingEnabled(False)
        item = self.contents_list_widget.item(0)
        item.setText(_translate("SettingDialog", "MQTT Connect"))
        item = self.contents_list_widget.item(1)
        item.setText(_translate("SettingDialog", "MQTT Broker"))
        self.contents_list_widget.setSortingEnabled(__sortingEnabled)
        self.broker_address_line_edit.setPlaceholderText(_translate("SettingDialog", "localhost"))
        self.label_2.setText(_translate("SettingDialog", "Port:"))
        self.label.setText(_translate("SettingDialog", "Broker Address:"))
        self.ok_push_button.setText(_translate("SettingDialog", "OK"))

import simulator.uiapplication.UiResource_rc
