# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SimulatorUI.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SimulatorUI(object):
    def setupUi(self, SimulatorUI):
        SimulatorUI.setObjectName("SimulatorUI")
        SimulatorUI.resize(636, 712)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/simulator.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        SimulatorUI.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(SimulatorUI)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_subscribe = QtWidgets.QWidget()
        self.tab_subscribe.setObjectName("tab_subscribe")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_subscribe)
        self.gridLayout_8.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.listWidgetSubscribe = QtWidgets.QListWidget(self.tab_subscribe)
        self.listWidgetSubscribe.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listWidgetSubscribe.setObjectName("listWidgetSubscribe")
        self.gridLayout_7.addWidget(self.listWidgetSubscribe, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_subscribe, "")
        self.tab_public = QtWidgets.QWidget()
        self.tab_public.setObjectName("tab_public")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.tab_public)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.pushButtonPublish = QtWidgets.QPushButton(self.tab_public)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButtonPublish.sizePolicy().hasHeightForWidth())
        self.pushButtonPublish.setSizePolicy(sizePolicy)
        self.pushButtonPublish.setObjectName("pushButtonPublish")
        self.gridLayout_9.addWidget(self.pushButtonPublish, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.listViewPublish = QtWidgets.QListView(self.tab_public)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listViewPublish.sizePolicy().hasHeightForWidth())
        self.listViewPublish.setSizePolicy(sizePolicy)
        self.listViewPublish.setObjectName("listViewPublish")
        self.gridLayout_9.addWidget(self.listViewPublish, 0, 1, 1, 1)
        self.groupBoxPublish = QtWidgets.QGroupBox(self.tab_public)
        self.groupBoxPublish.setObjectName("groupBoxPublish")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.groupBoxPublish)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.textEditPublishValue = QtWidgets.QTextEdit(self.groupBoxPublish)
        self.textEditPublishValue.setObjectName("textEditPublishValue")
        self.gridLayout_11.addWidget(self.textEditPublishValue, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.groupBoxPublish, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_public, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        SimulatorUI.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(SimulatorUI)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 636, 21))
        self.menubar.setObjectName("menubar")
        self.menu_File = QtWidgets.QMenu(self.menubar)
        self.menu_File.setObjectName("menu_File")
        SimulatorUI.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(SimulatorUI)
        self.statusbar.setObjectName("statusbar")
        SimulatorUI.setStatusBar(self.statusbar)
        self.dockWidget = QtWidgets.QDockWidget(SimulatorUI)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtWidgets.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.dockWidgetContents)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.treeViewTopic = QtWidgets.QTreeView(self.dockWidgetContents)
        self.treeViewTopic.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.treeViewTopic.setAlternatingRowColors(True)
        self.treeViewTopic.setObjectName("treeViewTopic")
        self.treeViewTopic.header().setSortIndicatorShown(False)
        self.gridLayout_5.addWidget(self.treeViewTopic, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        SimulatorUI.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.dockWidget_3 = QtWidgets.QDockWidget(SimulatorUI)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtWidgets.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.dockWidgetContents_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.textEditLog = QtWidgets.QTextEdit(self.dockWidgetContents_3)
        self.textEditLog.setEnabled(True)
        self.textEditLog.setReadOnly(True)
        self.textEditLog.setObjectName("textEditLog")
        self.gridLayout_3.addWidget(self.textEditLog, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        SimulatorUI.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockWidget_3)
        self.toolBar = QtWidgets.QToolBar(SimulatorUI)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName("toolBar")
        SimulatorUI.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionConnectMqtt = QtWidgets.QAction(SimulatorUI)
        self.actionConnectMqtt.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/connect.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionConnectMqtt.setIcon(icon1)
        self.actionConnectMqtt.setObjectName("actionConnectMqtt")
        self.actionSetting = QtWidgets.QAction(SimulatorUI)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/set.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSetting.setIcon(icon2)
        self.actionSetting.setObjectName("actionSetting")
        self.menubar.addAction(self.menu_File.menuAction())
        self.toolBar.addAction(self.actionConnectMqtt)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionSetting)

        self.retranslateUi(SimulatorUI)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(SimulatorUI)
        SimulatorUI.setTabOrder(self.textEditLog, self.tabWidget)
        SimulatorUI.setTabOrder(self.tabWidget, self.treeViewTopic)
        SimulatorUI.setTabOrder(self.treeViewTopic, self.listWidgetSubscribe)
        SimulatorUI.setTabOrder(self.listWidgetSubscribe, self.listViewPublish)

    def retranslateUi(self, SimulatorUI):
        _translate = QtCore.QCoreApplication.translate
        SimulatorUI.setWindowTitle(_translate("SimulatorUI", "Simulator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_subscribe), _translate("SimulatorUI", "Subscribe"))
        self.pushButtonPublish.setText(_translate("SimulatorUI", "Publish"))
        self.groupBoxPublish.setTitle(_translate("SimulatorUI", "Value"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_public), _translate("SimulatorUI", "Publish"))
        self.menu_File.setTitle(_translate("SimulatorUI", "&File"))
        self.dockWidget.setWindowTitle(_translate("SimulatorUI", "Topic tree"))
        self.dockWidget_3.setWindowTitle(_translate("SimulatorUI", "Log"))
        self.toolBar.setWindowTitle(_translate("SimulatorUI", "toolBar"))
        self.actionConnectMqtt.setText(_translate("SimulatorUI", "ConnectMqtt"))
        self.actionSetting.setText(_translate("SimulatorUI", "Setting"))

import Simulator_rc
